package net.henbit.yatagarasu;

import static java.awt.event.KeyEvent.*;
import static org.jnativehook.keyboard.NativeKeyEvent.*;

public class Utils
{

    public static final int UNDEFINED = -1;

    public static int getKeyEventKeyCode(int keycode)
    {
        switch (keycode)
        {
            case VC_ESCAPE:
                return VK_ESCAPE;
            case VC_F1:
                return VK_F1;
            case VC_F2:
                return VK_F2;
            case VC_F3:
                return VK_F3;
            case VC_F4:
                return VK_F4;
            case VC_F5:
                return VK_F5;
            case VC_F6:
                return VK_F6;
            case VC_F7:
                return VK_F7;
            case VC_F8:
                return VK_F8;
            case VC_F9:
                return VK_F9;
            case VC_F10:
                return VK_F10;
            case VC_F11:
                return VK_F11;
            case VC_F12:
                return VK_F12;
            case VC_BACKQUOTE:
                return VK_BACK_QUOTE;
            case VC_1:
                return VK_1;
            case VC_2:
                return VK_2;
            case VC_3:
                return VK_3;
            case VC_4:
                return VK_4;
            case VC_5:
                return VK_5;
            case VC_6:
                return VK_6;
            case VC_7:
                return VK_7;
            case VC_8:
                return VK_8;
            case VC_9:
                return VK_9;
            case VC_0:
                return VK_0;
            case VC_MINUS:
                return VK_MINUS;
            case VC_EQUALS:
                return VK_EQUALS;
            case VC_BACKSPACE:
                return VK_BACK_SPACE;
            case VC_TAB:
                return VK_TAB;
            case VC_CAPS_LOCK:
                return VK_CAPS_LOCK;
            case VC_A:
                return VK_A;
            case VC_B:
                return VK_B;
            case VC_C:
                return VK_C;
            case VC_D:
                return VK_D;
            case VC_E:
                return VK_E;
            case VC_F:
                return VK_F;
            case VC_G:
                return VK_G;
            case VC_H:
                return VK_H;
            case VC_I:
                return VK_I;
            case VC_J:
                return VK_J;
            case VC_K:
                return VK_K;
            case VC_L:
                return VK_L;
            case VC_M:
                return VK_M;
            case VC_N:
                return VK_N;
            case VC_O:
                return VK_O;
            case VC_P:
                return VK_P;
            case VC_Q:
                return VK_Q;
            case VC_R:
                return VK_R;
            case VC_S:
                return VK_S;
            case VC_T:
                return VK_T;
            case VC_U:
                return VK_U;
            case VC_V:
                return VK_V;
            case VC_W:
                return VK_W;
            case VC_X:
                return VK_X;
            case VC_Y:
                return VK_Y;
            case VC_Z:
                return VK_Z;
            case VC_OPEN_BRACKET:
                return VK_OPEN_BRACKET;
            case VC_CLOSE_BRACKET:
                return VK_CLOSE_BRACKET;
            case VC_BACK_SLASH:
                return VK_BACK_SLASH;
            case VC_SEMICOLON:
                return VK_SEMICOLON;
            case VC_QUOTE:
                return VK_QUOTE;
            case VC_ENTER:
                return VK_ENTER;
            case VC_COMMA:
                return VK_COMMA;
            case VC_PERIOD:
                return VK_PERIOD;
            case VC_SLASH:
                return VK_SLASH;
            case VC_SPACE:
                return VK_SPACE;
            case VC_PRINTSCREEN:
                return VK_PRINTSCREEN;
            case VC_SCROLL_LOCK:
                return VK_SCROLL_LOCK;
            case VC_PAUSE:
                return VK_PAUSE;
            case VC_INSERT:
                return VK_INSERT;
            case VC_DELETE:
                return VK_DELETE;
            case VC_HOME:
                return VK_HOME;
            case VC_END:
                return VK_END;
            case VC_PAGE_UP:
                return VK_PAGE_UP;
            case VC_PAGE_DOWN:
                return VK_PAGE_DOWN;
            case VC_UP:
                return VK_UP;
            case VC_LEFT:
                return VK_LEFT;
            case VC_CLEAR:
                return VK_CLEAR;
            case VC_RIGHT:
                return VK_RIGHT;
            case VC_DOWN:
                return VK_DOWN;
            case VC_NUM_LOCK:
                return VK_NUM_LOCK;
            case VC_SEPARATOR:
                return VK_SEPARATOR;
            case VC_SHIFT:
                return VK_SHIFT;
            case VC_CONTROL:
                return VK_CONTROL;
            case VC_ALT:
                return VK_ALT;
            case VC_META:
                return VK_META;
            case VC_CONTEXT_MENU:
                return VK_CONTEXT_MENU;
            case VC_KATAKANA:
                return VK_KATAKANA;
            case VC_UNDERSCORE:
                return VK_UNDERSCORE;
            case VC_KANJI:
                return VK_KANJI;
            case VC_HIRAGANA:
                return VK_HIRAGANA;
            default:
                return UNDEFINED;
        }
    }
}
